version: '3.8'

services:
  iptv-manager:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/content:/content
      - ${PWD}/hls:/hls
      - ${PWD}/cache:/cache
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - USE_GPU=auto
      - SERVER_URL=192.168.10.183  # URL du serveur
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/hls:/hls:ro
    depends_on:
      - iptv-manager
    restart: unless-stopped